language: python
python:
- '3.5'
- '3.6'
install: pip install --upgrade -r requirements.txt
script: python setup.py test
branches:
  only:
  - master
deploy:
  provider: pypi
  skip_existing: true
  user: alexschoeberl
  password:
    secure: B9JiobMrL6Pwxz3sksBRWjACz5zaUicbctnbXwn7OEUMxygA894ScuUMvBsV0OWOoMJnE6AYYJXmltZ7j5nfu2lI1D3OUSIop5FPQbxwnD4CwixcmqfnzwWYhz1v9mFDA4E5EcsCSZRVRo8Wi6D3hndDveDylgPz/8BIYeKf6CwhKSkbpM+K8rglUwF51nClyoM1X1VZ5gBJ9EYl1sovW0cZRVrxLO9znzcuhJG93kpEiJyQ9xSGwW/gmc+mLZPholK/xu9VUQCe2TeC6L7ns/l+4tSMim4B7j/5QFbqLQpDRsMxWcuHcrA7XI2JQAKqLnSWS+8mzZHHrzHwISBv7lUrJi+MlqDiiaQJXXaBNyEVt/OantSo3DjzRz4VedLTjbpkzSvMJKpTYVEcJuJ8Rup1WRPg0TS9PKLyDs2+7s+DeMeszIAl/BFMd6+AZ/SP0UEJ8YMRarlXEQeOHqDXQyDEJ3witcXQ+fhgsrqGcj6kbr2lake9eoqRwMaYpl/eqQ9Rm2nF5k5yVD4dAs61ErgaUaRGOlImT9Fwdch0hDCFBZIj74SPyJiAjhUh3lVZWVnWtgV5qfcohX2vDyVlEogPtTNP7tXr5ldD3i7Qmk4dlijShiG48rSux+fxll6bGa/R+T05EcB47UtkwyNzBPnmV0Ryw2kWFR/usV3A2EQ=
  true:
    branch: master
